import {ImageMetadata} from "~/global-common-typescript/typeDefinitions";

export const imageMetadataLibrary: {[relativePath: string]: ImageMetadata | undefined} = {
    "/livguard/battery images/IT 1048ST.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LtE,W.s:aLr?}Ys:nisA,@sosBo1",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1248ST.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LtE,Z^s:aKr?}Ys:nisA,@sosVo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1342ST.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LtE,Z^s:aKr?}Fs:nisA,@sosBo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1536FP.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LtE,Z^s:aKr?}Fs:nisA,@sosVo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1536TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LUEB%6$*kWae}tw{NGaK~CxGofRP",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1543STJ.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LaDulP%MR*s:~BxaR*n%x]t7aeay",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1548TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LZE.CVxaxux]^6soV@of~Cs:xat7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1550TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LRC64H$*V?s:}[s:RPjF-Vt7oen%",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1554STJ.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LcDbTr%2R*s:~CxuR*o1x]ozaeWB",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1554TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LXEU_st7oyxu}tofM{Wo}[X8kDtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1560TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LXELa6t7ofxu}togM{ay}[X8kWtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1584TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LZELHdxGOXoz~C%2S2tR-V%2R*xu",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1636STJ.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LbDk_a%MR*s:~CxuRjn%x[ozaeay",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1639TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LWEecJt8buxu}togM{Wo}[bboftR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1645TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LXEU_rt7oyxu}tofM{WV}[X8kCtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1666TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LWEeZDt7buxu}togM{WV~BbIogtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1860TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LTCFVRxaRPso}[xGRPn%-Bs:ayn*",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 1866TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LWEB?UtRX7tQ}tSgNGof}[bvXRtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 2048TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LYEo7At7tRxa^6ogIof6~CW;t7t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 2060TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LXEU}#xvs:tR}tR*Rjay}[kWogt7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 2066TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LWEefQt8bbxu}tofM{WV}]bboytR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 2266TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LWEecJt7g2xu}tofM{WV~CbIoftR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 2360TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LRCFk*$+V?s.}[s:RPjF-Vt6j@n+",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 2672TT.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LdDurixaR%xa~Cs:R*t7?HxaX8tR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery images/IT 9048ST.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LsEmUss:V@r?}FsojFsA,@sosUoL",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/bottom-bar/contact-us.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LBK1%f-;IU?b~q%Mxu%MM{M{M{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/bottom-bar/dealer-locator.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L8KK==~qfQ~q~qofoft7ayj[j[ay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/bottom-bar/home-inverter.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L8KK==~qfQ~q~qofj[ofofj[fQay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/bottom-bar/other-products.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L8KK==~qay~q~qofj[ofWBj[ayay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/category/batteries/1/1.jpg": {
        width: 3840,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L99GgpyD-;xa_N?Hxut7~W%Mxat7",
        placeholderColor: "#382828",
    },
    "/livguard/category/batteries/2/1.jpg": {
        width: 3840,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "L26Q^{#8KjEKK%9Z-pRj0|E1}]w|",
        placeholderColor: "#181818",
    },
    "/livguard/category/batteries/2/2.jpg": {
        width: 3841,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "LBBpU[waMys:?d%K%NRjNKxtM|Rj",
        placeholderColor: "#080838",
    },
    "/livguard/category/batteries/2/3.jpg": {
        width: 3840,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "L267o_:6~CiIpd4.^+MdcE56XmI:",
        placeholderColor: "#181818",
    },
    "/livguard/category/batteries/2/4.jpg": {
        width: 3841,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "LFBM=9~q9F00-;ozNGIV4nD%t7%M",
        placeholderColor: "#181818",
    },
    "/livguard/category/batteries/4/1.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LtE,Z^s:aKr?}Ys:nisA,@sosVo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/category/batteries/4/2.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LZELHdxGOXoz~C%2S2tR-V%2R*xu",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/category/batteries/6/hi-power-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LVC$G^%2Szog}[e.I:R*=eaKI:Rj",
        placeholderColor: "#080808",
    },
    "/livguard/category/batteries/6/rural-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LSD8:~-;o}-p}txaNas:].s;Naof",
        placeholderColor: "#080808",
    },
    "/livguard/category/batteries/6/super-life-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LKELdCaeFvM{}Z%256xu=fIA9tNF",
        placeholderColor: "#080808",
    },
    "/livguard/category/batteries/6/urban-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LQC5*hw{IoRP}t$*ELi_^QxGIojF",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/1/1.jpg": {
        width: 3840,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L154:MlT?b%gT{~BNYx]~Wpc-p%2",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/2/ai_charging.jpg": {
        width: 3841,
        height: 2249,
        altText: "Dummy alt text",
        blurHash: "L03bRB00=|^R_30K%ge:0e$*-;0K",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/2/dual_sensor_thermal.jpg": {
        width: 3841,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "LDIX:Piv4U-p~qI:kWbH4:WWodR*",
        placeholderColor: "#a8a8a8",
    },
    "/livguard/category/inverters/2/new_age_design.jpg": {
        width: 3840,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "L03[uM8w8wR5_N00?vNHD$4n~qWE",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/2/three_years_warranty.jpg": {
        width: 3840,
        height: 2248,
        altText: "Dummy alt text",
        blurHash: "L15hGTIEIB#O~p0Lbw-n014n^+?b",
        placeholderColor: "#181818",
    },
    "/livguard/category/inverters/4/1.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/4/2.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L17KuM?b_3D%009F%Mt700M{t79F",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/hi_power_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LVC$G^%2Szog}[e.I:R*=eaKI:Rj",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/rural_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LSD8:~-;o}-p}txaNas:].s;Naof",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/super_life_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LKELdCaeFvM{}Z%256xu=fIA9tNF",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/urban_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LQC5*hw{IoRP}t$*ELi_^QxGIojF",
        placeholderColor: "#080808",
    },
    "/livguard/contact form/contact_form_background.jpg": {
        width: 686,
        height: 768,
        altText: "Dummy alt text",
        blurHash: "L397eN?bof-;~qt7j[oft7fPj[j[",
        placeholderColor: "#484848",
    },
    "/livguard/favicon-128.png": {
        width: 128,
        height: 128,
        altText: "Dummy alt text",
        blurHash: "L~RJ{Q?^YO$j-pXmrsRPWBniWpkC",
        placeholderColor: "#e81828",
    },
    "/livguard/favicon-256.png": {
        width: 256,
        height: 256,
        altText: "Dummy alt text",
        blurHash: "L~RJ?A?^YP$j-pXmr?RPWBniWVf+",
        placeholderColor: "#e81828",
    },
    "/livguard/favicon-32.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L~RTg0?^lS$P%MXmniVtWBniW;of",
        placeholderColor: "#e81828",
    },
    "/livguard/favicon-512.png": {
        width: 512,
        height: 512,
        altText: "Dummy alt text",
        blurHash: "L~RJ?A?^cs$j-pTJr?VsWBniW;kC",
        placeholderColor: "#080808",
    },
    "/livguard/favicon-64.png": {
        width: 64,
        height: 64,
        altText: "Dummy alt text",
        blurHash: "L~RJ]I?^YP$j-pXmr?RPWBniWpkC",
        placeholderColor: "#e81828",
    },
    "/livguard/header/akshay.png": {
        width: 318,
        height: 438,
        altText: "Dummy alt text",
        blurHash: "LaHvYj}FE2W:I;NaI:NHKNK3Nvso",
        placeholderColor: "#080808",
    },
    "/livguard/header/logo-100-dark.jpg": {
        width: 100,
        height: 24,
        altText: "Dummy alt text",
        blurHash: "LSH.E5w{IUtl~qnjt7tR00NG%MM{",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/header/logo-100-light.jpg": {
        width: 100,
        height: 24,
        altText: "Dummy alt text",
        blurHash: "LQIOOp=|xuXm^+niIUX8~qxuIUxa",
        placeholderColor: "#e8e8e8",
    },
    "/livguard/home/1/1.jpg": {
        width: 390,
        height: 515,
        altText: "Dummy alt text",
        blurHash: "LBAmk[?F-nx].TxZtR%fo#R-n%t7",
        placeholderColor: "#787878",
    },
    "/livguard/home/11/1.jpg": {
        width: 1120,
        height: 798,
        altText: "Dummy alt text",
        blurHash: "LZGkn3%LxZxa~VxuxZWo^*t6oKWB",
        placeholderColor: "#d8c8a8",
    },
    "/livguard/home/11/2.jpg": {
        width: 1120,
        height: 798,
        altText: "Dummy alt text",
        blurHash: "L6Gt]IQ8Q8nC58t+.RR6HUY6M}Im",
        placeholderColor: "#a89888",
    },
    "/livguard/home/11/3.jpg": {
        width: 1122,
        height: 798,
        altText: "Dummy alt text",
        blurHash: "LEG[Zr~p-n?w5OxoNE-o%y%LIp-U",
        placeholderColor: "#a89898",
    },
    "/livguard/home/2/1.jpg": {
        width: 652,
        height: 442,
        altText: "Dummy alt text",
        blurHash: "LURC;}S~D%s;~qt7ofof_Nsoj[tR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/2/2.jpg": {
        width: 652,
        height: 442,
        altText: "Dummy alt text",
        blurHash: "LYNwct~q9GxuInM{%Lt700oMayIU",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/1-icon.png": {
        width: 76,
        height: 76,
        altText: "Dummy alt text",
        blurHash: "LsP%O.-;M{%M~qxuM{of00ofM{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/1.jpg": {
        width: 3841,
        height: 2113,
        altText: "Dummy alt text",
        blurHash: "LuH1;]aMD%Rj~pRkIUWA%zWXM{WB",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/2-icon.png": {
        width: 76,
        height: 76,
        altText: "Dummy alt text",
        blurHash: "LKS$ov~qxu~q_3ofxut7M{ayxuof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/2.jpg": {
        width: 3841,
        height: 2113,
        altText: "Dummy alt text",
        blurHash: "LWG8G+9aIUn%~pM{IUWXcYnhIUW=",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/3-icon.png": {
        width: 76,
        height: 76,
        altText: "Dummy alt text",
        blurHash: "LJS$ov~qM{~q_3ofM{j[IUfQM{WB",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/3.jpg": {
        width: 3841,
        height: 2113,
        altText: "Dummy alt text",
        blurHash: "LoH-}iD%D%Rj~qM{M{RjtRayR*WV",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/4-icon.png": {
        width: 76,
        height: 76,
        altText: "Dummy alt text",
        blurHash: "LSRp8-~q00_3WBxu9FofRjWBRjRj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/4.jpg": {
        width: 3841,
        height: 2113,
        altText: "Dummy alt text",
        blurHash: "LuHd]dE1NExb~BIoNGWB$_j^NKR%",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/5-icon.png": {
        width: 76,
        height: 76,
        altText: "Dummy alt text",
        blurHash: "LJS?DV~qfQ~q~qoffQofayfQfQfQ",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/5.jpg": {
        width: 3841,
        height: 2113,
        altText: "Dummy alt text",
        blurHash: "LmHBxiIAIUkC~pIUM{of%LWXR*Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/energy solution icons/1.png": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "LOI5Y--;M{%M~qxuM{of00ofM{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/energy solution icons/2.png": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "L9KBRF_3xu~q?bofxut7M{ayxuof",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/home/3/energy solution icons/3.png": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "L8KK==~qWB~q~qt7RjofRjj[Rjay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/home/3/energy solution icons/4.png": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "LAJRdV~q00_3WBt74nWBM{WBM{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/energy solution icons/5.png": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "L8KK==~qay~q~qofj[ofj[fQfQay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/home/4/1-desktop.jpg": {
        width: 3841,
        height: 2509,
        altText: "Dummy alt text",
        blurHash: "L48Mm#^Q000#ROV@ENJQ1HJ-}t}Y",
        placeholderColor: "#080808",
    },
    "/livguard/home/4/1-mobile.jpg": {
        width: 2583,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L89~vq^P0f1yIURjIpRj0zAX}[^5",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/1-bhk.png": {
        width: 48,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L03l8X%Ma}%M%MoLa}fln$jZa}a$",
        placeholderColor: "#181828",
    },
    "/livguard/home/5/1.png": {
        width: 370,
        height: 268,
        altText: "Dummy alt text",
        blurHash: "LMEV4]%gX-#m}ZtR9tn4+b9ZIUr?",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/2-bhk.png": {
        width: 49,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L14BqQ=iS0KZ]s,2R*Fo+*#tWBJz",
        placeholderColor: "#181828",
    },
    "/livguard/home/5/3-bhk.png": {
        width: 49,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L03bjxxvInxus:WBInaeRPWBM{ae",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/4-bhk.png": {
        width: 49,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L03S03%MIUxuWAj^IUWBMxf6M{WB",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/4.png": {
        width: 49,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L03S03%MIUxuWAj^IUWBMxf6M{WB",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/custom.png": {
        width: 49,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L03bjy%Meoxut7kCR*WBM{oLWAWB",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/step-1.png": {
        width: 48,
        height: 48,
        altText: "Dummy alt text",
        blurHash: "LESY{q?b9F~q-;9F9FIU4n4nD%IU",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/step-2.png": {
        width: 48,
        height: 48,
        altText: "Dummy alt text",
        blurHash: "LIS$ov~qRj_3~qRjM{ayM{RjWBM{",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/5/step-3.png": {
        width: 48,
        height: 48,
        altText: "Dummy alt text",
        blurHash: "LRSs50_3M{_3~qofxuofM{ayM{ay",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/5/villa.png": {
        width: 49,
        height: 49,
        altText: "Dummy alt text",
        blurHash: "L03bm,%Mjb%M%Mj]f8j[a}f8f7fQ",
        placeholderColor: "#181828",
    },
    "/livguard/home/6/1.jpg": {
        width: 1080,
        height: 1080,
        altText: "Dummy alt text",
        blurHash: "LyPsL$xu?w-pt7aet7t7o~oLaKWC",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/6/2.jpg": {
        width: 1080,
        height: 1080,
        altText: "Dummy alt text",
        blurHash: "LuM%yC%M?]%g~UoIxZt6E2S5RPoL",
        placeholderColor: "#f8f8e8",
    },
    "/livguard/home/6/3.jpg": {
        width: 1080,
        height: 1080,
        altText: "Dummy alt text",
        blurHash: "LFEL?8NfUG~VDOaIMxROC9Rlp0El",
        placeholderColor: "#080808",
    },
    "/livguard/home/6/4.jpg": {
        width: 1080,
        height: 1080,
        altText: "Dummy alt text",
        blurHash: "LCHA|R}r0i1$~U?G$$n~%}yC$j-7",
        placeholderColor: "#080808",
    },
    "/livguard/home/7/1.jpg": {
        width: 3215,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "LA7wQyKQ%3xapf-WtRoz%NXTkDof",
        placeholderColor: "#383848",
    },
    "/livguard/home/7/2.jpg": {
        width: 3216,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "LB6t,xtmxtt8%%-qt6t8-=tSt6t7",
        placeholderColor: "#080808",
    },
    "/livguard/home/7/3.jpg": {
        width: 3215,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L97,[IEmt7t7~TWaozs:^iSiozs:",
        placeholderColor: "#181818",
    },
    "/livguard/home/8/1.jpg": {
        width: 400,
        height: 400,
        altText: "Dummy alt text",
        blurHash: "L5BMV.E100^+}OoLGcRj1*-o+s4.",
        placeholderColor: "#383838",
    },
    "/livguard/home/8/2.jpg": {
        width: 400,
        height: 400,
        altText: "Dummy alt text",
        blurHash: "LCEnI*#m00-V3UOWMxEf{N$%-on5",
        placeholderColor: "#181818",
    },
    "/livguard/home/8/3.jpg": {
        width: 400,
        height: 400,
        altText: "Dummy alt text",
        blurHash: "LeI4Rnxa-:%K~9afxtxaI;azM|WC",
        placeholderColor: "#c8a878",
    },
    "/livguard/home/8/4.jpg": {
        width: 400,
        height: 400,
        altText: "Dummy alt text",
        blurHash: "L9EA4nv~0f}Z39kC:,6M$%E}I:#-",
        placeholderColor: "#181818",
    },
    "/livguard/icons/3dGrid.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LMS$ov?bD%_3~qofofof9FM{D%Rj",
        placeholderColor: "#080808",
    },
    "/livguard/icons/aiCharging.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LTSPX_?b4n?b~qxuxuof4nRj9FWB",
        placeholderColor: "#080808",
    },
    "/livguard/icons/battery_capacity.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LJRp8-~q00_3~qofRjoffQfQfQfQ",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/buyingGuide.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L8KBRF_3M{~q~qt7WBt7M{WBM{WB",
        placeholderColor: "#080808",
    },
    "/livguard/icons/capacity.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LFNdO8~q00IU_3IUD%%M00M{4n9F",
        placeholderColor: "#080808",
    },
    "/livguard/icons/confirmation.png": {
        width: 344,
        height: 306,
        altText: "Dummy alt text",
        blurHash: "LkPxCjxG9[w{}Fn%,ts:I:WVOrS2",
        placeholderColor: "#080808",
    },
    "/livguard/icons/dealer.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L8KK==~qj[~q~qofofofayj[j[ay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/icons/dimensions.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LMTI,a~qWB~q_3xuWBt7Rjt7WBof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/downloadCatalogue.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L7KBRF_39F~q~qIURjD%IUM{D%WB",
        placeholderColor: "#080808",
    },
    "/livguard/icons/enquire_now.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LaR{#?-;D%-;~qt7%Mt7D%WBIURj",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/flat-plate.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L00000fQfQfQfQfQfQfQfQfQfQfQ",
        placeholderColor: "#080808",
    },
    "/livguard/icons/inverter_capacity.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LKS$ov~qxu~q_3ofxut7M{ayxuof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/sineWave.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L5EfTi~q0000_3_3of4n00j[00IU",
        placeholderColor: "#080808",
    },
    "/livguard/icons/squareWave.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L4BzC40000~qD%-;WB9F?b%M00xu",
        placeholderColor: "#080808",
    },
    "/livguard/icons/tall-tubular.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L00000fQfQfQfQfQfQfQfQfQfQfQ",
        placeholderColor: "#080808",
    },
    "/livguard/icons/technology.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LKS~x5~qay~q~qt7j[t7WBj[ayfQ",
        placeholderColor: "#080808",
    },
    "/livguard/icons/waranty.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LRRW0b?b00-;~qj[%Mt700WB4nM{",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_0016_LGS2500.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L78;JiInXO-W~XX7J5$+=}o|J6-V",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_LGS2500.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L797R@InS_-D~DNZI.-C^ktRJ6-C",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_LGS3000.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L78;JhD%Sw-W~WbuJ5$S=}SzEe-C",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_LGS4000_A_Upload.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L98g$|?a-..9?w%LxUtTSjf4V=WZ",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_PS2500_4-Upload.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LND0Go?b?b?b~qWBRjRj%MM{D%IU",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_PS2500_5-Upload_with-Display.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LI9*44kWeTrr_NtRR5nO%#x]R5r=",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_PS4000_5-Upload---With-LCD.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L9BzIK?v?H=|_Nx]niVYyDbv4nVY",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/Inverter-power-verter-SQ_R.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L17KuM?b_3D%009F%Mt700M{t79F",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1700PV-SW-L.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LOC6+9t7IUxu~qozIUofxuj[WBa|",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1700PV-SW_.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LF8XOa%2IBbv_NsmIAXR.7oLM{oz",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/Livfast-PS-5000-F.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "LLBWe~-;%Mt7~q%Mt7ofxuofRjRk",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/Livguard-LGS1100iPV_power-verter-Inverter-Front.png": {
        width: 1100,
        height: 1100,
        altText: "Dummy alt text",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/1/hero_image.jpg": {
        width: 3840,
        height: 3841,
        altText: "Dummy alt text",
        blurHash: "LE84Pht7xut7~qxut7t7^+t7t7t7",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/1/section3/1.jpg": {
        width: 3840,
        height: 3841,
        altText: "Dummy alt text",
        blurHash: "L47A;]Q-=|$j_N9tOENtxuIoxuR*",
        placeholderColor: "#383838",
    },
    "/livguard/landingPages/1/section3/2.jpg": {
        width: 3840,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L27T,]}a}@$+yCkq%fIUtli^I:t8",
        placeholderColor: "#483838",
    },
    "/livguard/landingPages/1/section3/3.jpg": {
        width: 3840,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L36aSIml^kv~?^56k=Io%hIUofR*",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/2/hero_image.jpg": {
        width: 3840,
        height: 3841,
        altText: "Dummy alt text",
        blurHash: "LGB3W+%M%2xu~X%2t7t7~WtRofof",
        placeholderColor: "#484848",
    },
    "/livguard/landingPages/2/other_brands.png": {
        width: 100,
        height: 100,
        altText: "Dummy alt text",
        blurHash: "LAFiPk}]9H?a0M0LrsM|MJD~IUs=",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/3/1.jpg": {
        width: 3840,
        height: 2934,
        altText: "Dummy alt text",
        blurHash: "L37^fB8^9teT?v0e^+Io~WD*s.WB",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/3/2.jpg": {
        width: 3840,
        height: 2935,
        altText: "Dummy alt text",
        blurHash: "L8A0UY-W=x-W~qEMt7Na-;IoWUWX",
        placeholderColor: "#585858",
    },
    "/livguard/landingPages/3/3.jpg": {
        width: 3840,
        height: 2935,
        altText: "Dummy alt text",
        blurHash: "L16a6hH?5k],5+MxyX9[.8IUaLni",
        placeholderColor: "#381818",
    },
    "/livguard/landingPages/3/hero_image.jpg": {
        width: 3840,
        height: 3840,
        altText: "Dummy alt text",
        blurHash: "L88p.V%g-pxu~q?Hxvt7~W%Mxuof",
        placeholderColor: "#382828",
    },
    "/livguard/load-calculator/1.jpg": {
        width: 4973,
        height: 3306,
        altText: "Dummy alt text",
        blurHash: "LA9Z+PRj01f+~VRj9GoybbNGoJxt",
        placeholderColor: "#282818",
    },
    "/livguard/logo-128.png": {
        width: 128,
        height: 31,
        altText: "Dummy alt text",
        blurHash: "L~R{c9xGae%g~qn%j]t7WVfkj[fk",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/logo-256.png": {
        width: 256,
        height: 63,
        altText: "Dummy alt text",
        blurHash: "L|R{c9xGae%g~qjZkCt7WBbHkCfk",
        placeholderColor: "#080808",
    },
    "/livguard/logo-32.png": {
        width: 32,
        height: 8,
        altText: "Dummy alt text",
        blurHash: "L{R.=R$*WByD~qs:j[ozRjofa|a|",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/logo-512.png": {
        width: 512,
        height: 126,
        altText: "Dummy alt text",
        blurHash: "L~R.[ZxGae%g~qn%kCt7WBbHkCj[",
        placeholderColor: "#080808",
    },
    "/livguard/logo-64.png": {
        width: 64,
        height: 16,
        altText: "Dummy alt text",
        blurHash: "L]R.[Z$jjZ%g~qoLoftRRjfkofj[",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LG1150i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1150i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1150i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1150i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1150i/Infographic/Square-wave-Inverters_492-x-492-px_1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG1150i/Infographic/Square-wave-Inverters_492-x-492-px_2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1150i/Infographic/Square-wave-Inverters_492-x-492-px_3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1150i/Infographic/Square-wave-Inverters_LG1150i_492-x-492-px.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%%K%rr+^{f0{M{=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1450i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw|",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1450i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1450i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1450i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1450i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%*K%rr+^{f0{M{=yO?I:NGoz",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1450i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1450i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1450i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG1550i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0EzM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1550i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1550i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1550i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1550i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%*K%rr+^{f0{M{=yO?I:NGoz",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1550i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1550i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1550i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG1950i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw|",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1950i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1950i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1950i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1950i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%%K%rr+^{f0{M{=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1950i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1950i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1950i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG750i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG750i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG750i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG750i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG750i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%*PArr+^{f0{NF=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG750i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG750i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG750i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG850i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG850i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG850i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG850i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG850i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%*K%rr+^{f0{NF=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG850i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG850i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG850i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG950i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG950i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG950i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG950i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG950i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "L9CE%%K%rr+^{f0{M{=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG950i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG950i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG950i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1000i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "L$Kdxp-p%Moz~qn%axozkBRjRPni",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1000i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LjNw4kIntQ%1~qxuM{NGtRWBV@t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1000i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LWM%cf8_bv?H~Bs:NGM{o#oeV[WB",
        placeholderColor: "#c8b8a8",
    },
    "/livguard/product/inverter/LGS1000i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLzmq4U%}-V~qxbIUNGyY%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1000i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LyLNlY?Hxuoz~qj[aeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1000i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOf[Uax%M,=~q%MM{Io?vt7M{kW",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1000i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LROyz{4mSN?H~AxaNGM{NcWVV@jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1000i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLL;BQ4.t,-C~q%2MxRj.TxYQ-Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1100i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "L$Kd#w-p%Moz~qo0axozkBRjRPni",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1100i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LjNw4kIntQ%1~qxuM{NGtRWBV@t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1100i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LWM%cf8_bv?H~Bs:NGM{o#oeV[WB",
        placeholderColor: "#c8b8a8",
    },
    "/livguard/product/inverter/LGS1100i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLzmq4U%}-V~qxbIUNGyY%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1100i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LyLNlY?Hxuoz~qj[aeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1100i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOf[Uax%M,=~q%MM{Io?vt7M{kW",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1100i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LROyz{4mSN?H~AxaNGM{NcWVV@jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1100i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLL;BQ4.t,-C~q%2MxRj.TxYQ-Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1600/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "L%Kd#x-p%2oz~qn%ayozkBRjRPjF",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1600/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LcN^G1Int7$%~qxaM{WB-;s:M{bI",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1600/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LUM@1F8_bv?H~Bs.NGM{kWa{WBa#",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LGS1600/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLzmq4U%}-V~qxaIUNGyY%1MKNa",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1600/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LyLE4-?Hxuoz~qjtaeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1600/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LPO:Ry8^Sg?H~AxZM{M{I=WCV[oM",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1600/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOf[UWUxv$M~q-pRPM{?vt7Mxg3",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1600/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LMLzmr9Ft,-B~q%2MxR*.Tt4Q-R*",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1700/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "L$Kd#w-p%2oz~qn%ayozj[RjRPjF",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1700/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LcN^G1Int7$%~qxaM{WB-;s:M{bI",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1700/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LUM@1F8_bv?H~Bs.NGM{kWa{WBa#",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LGS1700/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLzmq4U%}-V~qxaIUNGyY%1MKNa",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1700/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LyLE4-?Hxuoz~qjtaeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1700/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LPO:Ry8^Sg?H~AxZM{M{I=WCV[oM",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1700/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOf[UWUxv$M~q-pRPM{?vt7Mxg3",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1700/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LMLzmr9Ft,-B~q%2MxR*.Tt4Q-R*",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS900i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "L$Kd#w-p%Moz~qo0axozkBRjRPn$",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS900i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LjNw4kIntQ%1~qxuM{NGtRWBV@t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS900i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LWM%cf8_bv?H~Bs:NGM{o#oeV[WB",
        placeholderColor: "#c8b8a8",
    },
    "/livguard/product/inverter/LGS900i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "Dummy alt text",
        blurHash: "LOLzmq4U%}-V~qxbIUNGyY%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS900i/Infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LLL;BQ4.t,-C~q%2MxRj.TxYQ-Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS900i/Infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LROyz{4mSN?H~AxaNGM{NcWVV@jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS900i/Infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LSOf[Uax%M,=~q%MM{Io?vt7M{kW",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS900i/Infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "Dummy alt text",
        blurHash: "LyLNlY?Hxuoz~qj[aeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/temp/Load calculator Bg.jpg": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "LZPyGJ_3S##-|IniWBo1rDRPayoL",
        placeholderColor: "#d88888",
    },
    "/livguard/temp/Load calculator needle.png": {
        width: 56,
        height: 56,
        altText: "Dummy alt text",
        blurHash: "LeG+UM~qD%RjM{M{RjWB009F%Mof",
        placeholderColor: "#080808",
    },
    "/livguard/icons/sine wave white.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "L8K_E~~q00_3?b004n?b00D%0000",
        placeholderColor: "#080808",
    },
    "/livguard/icons/square wave white.png": {
        width: 32,
        height: 32,
        altText: "Dummy alt text",
        blurHash: "LIN,_D~qM{?b?bM{IUxu00IU4nM{",
        placeholderColor: "#080808",
    },
};
