import {ImageMetadata} from "~/global-common-typescript/typeDefinitions";

export const imageMetadataLibrary: {[relativePath: string]: ImageMetadata | undefined} = {
    "/livguard/battery-images/IT1048ST.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LtE,W.s:aLr?}Ys:nisA,@sosBo1",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1248ST.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LtE,Z^s:aKr?}Ys:nisA,@sosVo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1342ST.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LtE,Z^s:aKr?}Fs:nisA,@sosBo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1536FP.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LtE,Z^s:aKr?}Fs:nisA,@sosVo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1536TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LUEB%6$*kWae}tw{NGaK~CxGofRP",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1543STJ.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LaDulP%MR*s:~BxaR*n%x]t7aeay",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1548TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LZE.CVxaxux]^6soV@of~Cs:xat7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1550TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LRC64H$*V?s:}[s:RPjF-Vt7oen%",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1554STJ.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LcDbTr%2R*s:~CxuR*o1x]ozaeWB",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1554TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LXEU_st7oyxu}tofM{Wo}[X8kDtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1560TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LXELa6t7ofxu}togM{ay}[X8kWtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1584TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LZELHdxGOXoz~C%2S2tR-V%2R*xu",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1636STJ.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LbDk_a%MR*s:~CxuRjn%x[ozaeay",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1639TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LWEecJt8buxu}togM{Wo}[bboftR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1645TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LXEU_rt7oyxu}tofM{WV}[X8kCtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1666TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LWEeZDt7buxu}togM{WV~BbIogtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1860TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LTCFVRxaRPso}[xGRPn%-Bs:ayn*",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT1866TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LWEB?UtRX7tQ}tSgNGof}[bvXRtR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT2048TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LYEo7At7tRxa^6ogIof6~CW;t7t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT2060TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LXEU}#xvs:tR}tR*Rjay}[kWogt7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT2066TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LWEefQt8bbxu}tofM{WV}]bboytR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT2266TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LWEecJt7g2xu}tofM{WV~CbIoftR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT2360TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LRCFk*$+V?s.}[s:RPjF-Vt6j@n+",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT2672TT.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LdDurixaR%xa~Cs:R*t7?HxaX8tR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/battery-images/IT9048ST.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LsEmUss:V@r?}FsojFsA,@sosUoL",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/bottom-bar/contact-us.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LBK1%f-;IU?b~q%Mxu%MM{M{M{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/bottom-bar/dealer-locator.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L8KK==~qfQ~q~qofoft7ayj[j[ay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/bottom-bar/home-inverter.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L8KK==~qfQ~q~qofj[ofofj[fQay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/bottom-bar/other-products.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L8KK==~qay~q~qofj[ofWBj[ayay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/category/batteries/1/1.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L99GgpyD-;xa_N?Hxut7~W%Mxat7",
        placeholderColor: "#382828",
    },
    "/livguard/category/batteries/2/1.jpg": {
        width: 3840,
        height: 2248,
        altText: "",
        blurHash: "L26Q^{#8KjEKK%9Z-pRj0|E1}]w|",
        placeholderColor: "#181818",
    },
    "/livguard/category/batteries/2/2.jpg": {
        width: 3841,
        height: 2248,
        altText: "",
        blurHash: "LBBpU[waMys:?d%K%NRjNKxtM|Rj",
        placeholderColor: "#080838",
    },
    "/livguard/category/batteries/2/3.jpg": {
        width: 3840,
        height: 2248,
        altText: "",
        blurHash: "L267o_:6~CiIpd4.^+MdcE56XmI:",
        placeholderColor: "#181818",
    },
    "/livguard/category/batteries/2/4.jpg": {
        width: 3841,
        height: 2248,
        altText: "",
        blurHash: "LFBM=9~q9F00-;ozNGIV4nD%t7%M",
        placeholderColor: "#181818",
    },
    "/livguard/category/batteries/4/1.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LtE,Z^s:aKr?}Ys:nisA,@sosVo2",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/category/batteries/4/2.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LZELHdxGOXoz~C%2S2tR-V%2R*xu",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/category/batteries/6/hi-power-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LVC$G^%2Szog}[e.I:R*=eaKI:Rj",
        placeholderColor: "#080808",
    },
    "/livguard/category/batteries/6/rural-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LSD8:~-;o}-p}txaNas:].s;Naof",
        placeholderColor: "#080808",
    },
    "/livguard/category/batteries/6/super-life-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LKELdCaeFvM{}Z%256xu=fIA9tNF",
        placeholderColor: "#080808",
    },
    "/livguard/category/batteries/6/urban-jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LQC5*hw{IoRP}t$*ELi_^QxGIojF",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/1/1.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L154:MlT?b%gT{~BNYx]~Wpc-p%2",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/2/ai_charging.jpg": {
        width: 3841,
        height: 2249,
        altText: "",
        blurHash: "L03bRB00=|^R_30K%ge:0e$*-;0K",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/2/dual_sensor_thermal.jpg": {
        width: 3841,
        height: 2248,
        altText: "",
        blurHash: "LDIX:Piv4U-p~qI:kWbH4:WWodR*",
        placeholderColor: "#a8a8a8",
    },
    "/livguard/category/inverters/2/new_age_design.jpg": {
        width: 3840,
        height: 2248,
        altText: "",
        blurHash: "L03[uM8w8wR5_N00?vNHD$4n~qWE",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/2/three_years_warranty.jpg": {
        width: 3840,
        height: 2248,
        altText: "",
        blurHash: "L15hGTIEIB#O~p0Lbw-n014n^+?b",
        placeholderColor: "#181818",
    },
    "/livguard/category/inverters/4/1.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/category/inverters/4/2.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L17KuM?b_3D%009F%Mt700M{t79F",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/hi_power_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LVC$G^%2Szog}[e.I:R*=eaKI:Rj",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/rural_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LSD8:~-;o}-p}txaNas:].s;Naof",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/super_life_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LKELdCaeFvM{}Z%256xu=fIA9tNF",
        placeholderColor: "#080808",
    },
    "/livguard/category/jodi/urban_jodi.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LQC5*hw{IoRP}t$*ELi_^QxGIojF",
        placeholderColor: "#080808",
    },
    "/livguard/contact form/contact_form_background.jpg": {
        width: 686,
        height: 768,
        altText: "",
        blurHash: "L397eN?bof-;~qt7j[oft7fPj[j[",
        placeholderColor: "#484848",
    },
    "/livguard/favicon-128.jpg": {
        width: 128,
        height: 128,
        altText: "",
        blurHash: "LePrd?5PQ7^QZ$OraerD.8%2e9S#",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/favicon-128.png": {
        width: 128,
        height: 128,
        altText: "",
        blurHash: "L~RJ{Q?^YO$j-pXmrsRPWBniWpkC",
        placeholderColor: "#e81828",
    },
    "/livguard/favicon-256.jpg": {
        width: 256,
        height: 256,
        altText: "",
        blurHash: "LaPYMI0yLz^6Z$O?aKvg.8%Mn4XS",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/favicon-256.png": {
        width: 256,
        height: 256,
        altText: "",
        blurHash: "L~RJ?A?^YP$j-pXmr?RPWBniWVf+",
        placeholderColor: "#e81828",
    },
    "/livguard/favicon-32.jpg": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LfPO-,56Ua^QZ$OraerD%#%2idS#",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/favicon-32.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L~RTg0?^lS$P%MXmniVtWBniW;of",
        placeholderColor: "#e81828",
    },
    "/livguard/favicon-512.jpg": {
        width: 512,
        height: 512,
        altText: "",
        blurHash: "LbPYPQ0yLz^6Z$O=aKrD.8%MiwXS",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/favicon-512.png": {
        width: 512,
        height: 512,
        altText: "",
        blurHash: "L~RJ?A?^cs$j-pTJr?VsWBniW;kC",
        placeholderColor: "#080808",
    },
    "/livguard/favicon-64.jpg": {
        width: 64,
        height: 64,
        altText: "",
        blurHash: "LfPh^G5PQ7^QZ$OraerD.8%2icS#",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/favicon-64.png": {
        width: 64,
        height: 64,
        altText: "",
        blurHash: "L~RJ]I?^YP$j-pXmr?RPWBniWpkC",
        placeholderColor: "#e81828",
    },
    "/livguard/header/akshay.png": {
        width: 318,
        height: 438,
        altText: "",
        blurHash: "LaHvYj}FE2W:I;NaI:NHKNK3Nvso",
        placeholderColor: "#080808",
    },
    "/livguard/header/logo-100-dark.jpg": {
        width: 100,
        height: 24,
        altText: "",
        blurHash: "LSH.E5w{IUtl~qnjt7tR00NG%MM{",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/header/logo-100-light.jpg": {
        width: 100,
        height: 24,
        altText: "",
        blurHash: "LQIOOp=|xuXm^+niIUX8~qxuIUxa",
        placeholderColor: "#e8e8e8",
    },
    "/livguard/hero-banners/category-battery-hero-desktop.jpg": {
        width: 3840,
        height: 2161,
        altText: "",
        blurHash: "L68:*UY5^+x]?w^ktlt7_3%Mt7t7",
        placeholderColor: "#383838",
    },
    "/livguard/hero-banners/category-battery-hero-mobile.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L99GgpyD-;xa_N?Hxut7~W%Mxat7",
        placeholderColor: "#382828",
    },
    "/livguard/hero-banners/category-inverter-hero-desktop.jpg": {
        width: 3840,
        height: 2160,
        altText: "",
        blurHash: "L14xA1C5-VtRGt}[Or%M~Ctm-Vxa",
        placeholderColor: "#080808",
    },
    "/livguard/hero-banners/category-inverter-hero-mobile.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L154:MlT?b%gT{~BNYx]~Wpc-p%2",
        placeholderColor: "#080808",
    },
    "/livguard/hero-banners/lp-1-hero-desktop.jpg": {
        width: 3840,
        height: 2160,
        altText: "",
        blurHash: "L97wg7tl-;xu~q-px]xu-;xut7xa",
        placeholderColor: "#080808",
    },
    "/livguard/hero-banners/lp-1-hero-mobile.jpg": {
        width: 3840,
        height: 3841,
        altText: "",
        blurHash: "L86HcbtRxut7~X%Mxuoz^+xvt7t7",
        placeholderColor: "#080808",
    },
    "/livguard/hero-banners/lp-2-hero-desktop.jpg": {
        width: 3840,
        height: 2161,
        altText: "",
        blurHash: "L9A0ap.8?b%2~X%2xuxu~Wt6bHt7",
        placeholderColor: "#584848",
    },
    "/livguard/hero-banners/lp-2-hero-mobile.jpg": {
        width: 3840,
        height: 3841,
        altText: "",
        blurHash: "LGB3W+%M%2xu~X%2t7t7~WtRofof",
        placeholderColor: "#484848",
    },
    "/livguard/hero-banners/lp-3-desktop.jpg": {
        width: 3840,
        height: 2161,
        altText: "",
        blurHash: "L99Q5P.8?H-p~q?H%Mxu?H%Mt7of",
        placeholderColor: "#584848",
    },
    "/livguard/hero-banners/lp-3-mobile.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L88p.V%g-pxu~q?Hxvt7~W%Mxuof",
        placeholderColor: "#382828",
    },
    "/livguard/home/1/1.jpg": {
        width: 390,
        height: 515,
        altText: "",
        blurHash: "LBAmk[?F-nx].TxZtR%fo#R-n%t7",
        placeholderColor: "#787878",
    },
    "/livguard/home/10/1-dark.jpg": {
        "width": 974,
        "height": 1080,
        "altText": "Dummy alt text",
        "blurHash": "L02=o*=|ELEf%2oLWVWV9tNa$*xG",
        "placeholderColor": "#181818"
    },
    "/livguard/home/10/1-light.jpg": {
        "width": 974,
        "height": 1080,
        "altText": "Dummy alt text",
        "blurHash": "LQS$ov?bxu~q?bofj[of%Mt7RjWB",
        "placeholderColor": "#f8f8f8"
    },
    "/livguard/home/11/1.jpg": {
        width: 1120,
        height: 798,
        altText: "",
        blurHash: "LZGkn3%LxZxa~VxuxZWo^*t6oKWB",
        placeholderColor: "#d8c8a8",
    },
    "/livguard/home/11/2.jpg": {
        width: 1120,
        height: 798,
        altText: "",
        blurHash: "L6Gt]IQ8Q8nC58t+.RR6HUY6M}Im",
        placeholderColor: "#a89888",
    },
    "/livguard/home/11/3.jpg": {
        width: 1122,
        height: 798,
        altText: "",
        blurHash: "LEG[Zr~p-n?w5OxoNE-o%y%LIp-U",
        placeholderColor: "#a89898",
    },
    "/livguard/home/2/1.jpg": {
        width: 652,
        height: 442,
        altText: "",
        blurHash: "LURC;}S~D%s;~qt7ofof_Nsoj[tR",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/2/2.jpg": {
        width: 652,
        height: 442,
        altText: "",
        blurHash: "LYNwct~q9GxuInM{%Lt700oMayIU",
        placeholderColor: "#f8f8f8",
    },

    "/livguard/home/3/1-icon.png": {
        width: 76,
        height: 76,
        altText: "",
        blurHash: "LsP%O.-;M{%M~qxuM{of00ofM{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/1.jpg": {
        width: 3841,
        height: 2113,
        altText: "",
        blurHash: "LuH1;]aMD%Rj~pRkIUWA%zWXM{WB",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/2-icon.png": {
        width: 76,
        height: 76,
        altText: "",
        blurHash: "LKS$ov~qxu~q_3ofxut7M{ayxuof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/2.jpg": {
        width: 3841,
        height: 2113,
        altText: "",
        blurHash: "LoH-}iD%D%Rj~qM{M{RjtRayR*WV",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/3-icon.png": {
        width: 76,
        height: 76,
        altText: "",
        blurHash: "LJS$ov~qM{~q_3ofM{j[IUfQM{WB",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/3.jpg": {
        width: 3841,
        height: 2113,
        altText: "",
        blurHash: "LWG8G+9aIUn%~pM{IUWXcYnhIUW=",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/4-icon.png": {
        width: 76,
        height: 76,
        altText: "",
        blurHash: "LSRp8-~q00_3WBxu9FofRjWBRjRj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/4.jpg": {
        width: 3841,
        height: 2113,
        altText: "",
        blurHash: "LuHd]dE1NExb~BIoNGWB$_j^NKR%",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/5-icon.png": {
        width: 76,
        height: 76,
        altText: "",
        blurHash: "LJS?DV~qfQ~q~qoffQofayfQfQfQ",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/3/5.jpg": {
        width: 3841,
        height: 2113,
        altText: "",
        blurHash: "LmHBxiIAIUkC~pIUM{of%LWXR*Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/energy solution icons/1.png": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "LOI5Y--;M{%M~qxuM{of00ofM{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/energy solution icons/2.png": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "L9KBRF_3xu~q?bofxut7M{ayxuof",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/home/3/energy solution icons/3.png": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "L8KK==~qWB~q~qt7RjofRjj[Rjay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/home/3/energy solution icons/4.png": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "LAJRdV~q00_3WBt74nWBM{WBM{Rj",
        placeholderColor: "#080808",
    },
    "/livguard/home/3/energy solution icons/5.png": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "L8KK==~qay~q~qofj[ofj[fQfQay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/home/4/1-desktop.jpg": {
        width: 3841,
        height: 2509,
        altText: "",
        blurHash: "L48Mm#^Q000#ROV@ENJQ1HJ-}t}Y",
        placeholderColor: "#080808",
    },
    "/livguard/home/4/1-mobile.jpg": {
        width: 1712,
        height: 1116,
        altText: "",
        blurHash: "L796RL0}xt}s0f,?WB9]5*ofa$X9",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/1-bhk.png": {
        width: 48,
        height: 49,
        altText: "",
        blurHash: "L03l8X%Ma}%M%MoLa}fln$jZa}a$",
        placeholderColor: "#181828",
    },
    "/livguard/home/5/1.png": {
        width: 370,
        height: 268,
        altText: "",
        blurHash: "LMEV4]%gX-#m}ZtR9tn4+b9ZIUr?",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/2-bhk.png": {
        width: 49,
        height: 49,
        altText: "",
        blurHash: "L14BqQ=iS0KZ]s,2R*Fo+*#tWBJz",
        placeholderColor: "#181828",
    },
    "/livguard/home/5/3-bhk.png": {
        width: 49,
        height: 49,
        altText: "",
        blurHash: "L03bjxxvInxus:WBInaeRPWBM{ae",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/4-bhk.png": {
        width: 49,
        height: 49,
        altText: "",
        blurHash: "L03S03%MIUxuWAj^IUWBMxf6M{WB",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/4.png": {
        width: 49,
        height: 49,
        altText: "",
        blurHash: "L03S03%MIUxuWAj^IUWBMxf6M{WB",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/custom.png": {
        width: 49,
        height: 49,
        altText: "",
        blurHash: "L03bjy%Meoxut7kCR*WBM{oLWAWB",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/step-1.png": {
        width: 48,
        height: 48,
        altText: "",
        blurHash: "LESY{q?b9F~q-;9F9FIU4n4nD%IU",
        placeholderColor: "#080808",
    },
    "/livguard/home/5/step-2.png": {
        width: 48,
        height: 48,
        altText: "",
        blurHash: "LIS$ov~qRj_3~qRjM{ayM{RjWBM{",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/5/step-3.png": {
        width: 48,
        height: 48,
        altText: "",
        blurHash: "LRSs50_3M{_3~qofxuofM{ayM{ay",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/5/villa.png": {
        width: 49,
        height: 49,
        altText: "",
        blurHash: "L03bm,%Mjb%M%Mj]f8j[a}f8f7fQ",
        placeholderColor: "#181828",
    },
    "/livguard/home/6/1.jpg": {
        width: 1080,
        height: 1080,
        altText: "",
        blurHash: "LyPsL$xu?w-pt7aet7t7o~oLaKWC",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/home/6/2.jpg": {
        width: 1080,
        height: 1080,
        altText: "",
        blurHash: "LuM%yC%M?]%g~UoIxZt6E2S5RPoL",
        placeholderColor: "#f8f8e8",
    },
    "/livguard/home/6/3.jpg": {
        width: 1080,
        height: 1080,
        altText: "",
        blurHash: "LFEL?8NfUG~VDOaIMxROC9Rlp0El",
        placeholderColor: "#080808",
    },
    "/livguard/home/6/4.jpg": {
        width: 1080,
        height: 1080,
        altText: "",
        blurHash: "LCHA|R}r0i1$~U?G$$n~%}yC$j-7",
        placeholderColor: "#080808",
    },
    "/livguard/home/7/1.jpg": {
        width: 3215,
        height: 3840,
        altText: "",
        blurHash: "LA7wQyKQ%3xapf-WtRoz%NXTkDof",
        placeholderColor: "#383848",
    },
    "/livguard/home/7/2.jpg": {
        width: 3216,
        height: 3840,
        altText: "",
        blurHash: "LB6t,xtmxtt8%%-qt6t8-=tSt6t7",
        placeholderColor: "#080808",
    },
    "/livguard/home/7/3.jpg": {
        width: 3215,
        height: 3840,
        altText: "",
        blurHash: "L97,[IEmt7t7~TWaozs:^iSiozs:",
        placeholderColor: "#181818",
    },
    "/livguard/home/8/1.jpg": {
        width: 400,
        height: 400,
        altText: "",
        blurHash: "L5BMV.E100^+}OoLGcRj1*-o+s4.",
        placeholderColor: "#383838",
    },
    "/livguard/home/8/2.jpg": {
        width: 400,
        height: 400,
        altText: "",
        blurHash: "LCEnI*#m00-V3UOWMxEf{N$%-on5",
        placeholderColor: "#181818",
    },
    "/livguard/home/8/3.jpg": {
        width: 400,
        height: 400,
        altText: "",
        blurHash: "LeI4Rnxa-:%K~9afxtxaI;azM|WC",
        placeholderColor: "#c8a878",
    },
    "/livguard/home/8/4.jpg": {
        width: 400,
        height: 400,
        altText: "",
        blurHash: "L9EA4nv~0f}Z39kC:,6M$%E}I:#-",
        placeholderColor: "#181818",
    },
    "/livguard/icons/3dGrid.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LMS$ov?bD%_3~qofofof9FM{D%Rj",
        placeholderColor: "#080808",
    },
    "/livguard/icons/aiCharging.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LTSPX_?b4n?b~qxuxuof4nRj9FWB",
        placeholderColor: "#080808",
    },
    "/livguard/icons/battery_capacity.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LJRp8-~q00_3~qofRjoffQfQfQfQ",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/buyingGuide.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L8KBRF_3M{~q~qt7WBt7M{WBM{WB",
        placeholderColor: "#080808",
    },
    "/livguard/icons/capacity.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LFNdO8~q00IU_3IUD%%M00M{4n9F",
        placeholderColor: "#080808",
    },
    "/livguard/icons/confirmation.png": {
        width: 344,
        height: 306,
        altText: "",
        blurHash: "LkPxCjxG9[w{}Fn%,ts:I:WVOrS2",
        placeholderColor: "#080808",
    },
    "/livguard/icons/dealer.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L8KK==~qj[~q~qofofofayj[j[ay",
        placeholderColor: "#b8b8b8",
    },
    "/livguard/icons/dimensions.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LMTI,a~qWB~q_3xuWBt7Rjt7WBof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/downloadCatalogue.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L7KBRF_39F~q~qIURjD%IUM{D%WB",
        placeholderColor: "#080808",
    },
    "/livguard/icons/enquire_now.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LaR{#?-;D%-;~qt7%Mt7D%WBIURj",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/flat plate white.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LLT9L#~qxu~q_3ofxut7M{ayxuof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/flat-plate.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L00000fQfQfQfQfQfQfQfQfQfQfQ",
        placeholderColor: "#080808",
    },
    "/livguard/icons/inverter_capacity.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LKS$ov~qxu~q_3ofxut7M{ayxuof",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/sine wave white.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L8K_E~~q00_3?b004n?b00D%0000",
        placeholderColor: "#080808",
    },
    "/livguard/icons/sineWave.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L5EfTi~q0000_3_3of4n00j[00IU",
        placeholderColor: "#080808",
    },
    "/livguard/icons/square wave white.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LIN,_D~qM{?b?bM{IUxu00IU4nM{",
        placeholderColor: "#080808",
    },
    "/livguard/icons/squareWave.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L4BzC40000~qD%-;WB9F?b%M00xu",
        placeholderColor: "#080808",
    },
    "/livguard/icons/tall tubular white.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LKTSUA~qfQ~q~qoffQofayfQfQfQ",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/icons/tall-tubular.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "L00000fQfQfQfQfQfQfQfQfQfQfQ",
        placeholderColor: "#080808",
    },
    "/livguard/icons/technology.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LKS~x5~qay~q~qt7j[t7WBj[ayfQ",
        placeholderColor: "#080808",
    },
    "/livguard/icons/waranty.png": {
        width: 32,
        height: 32,
        altText: "",
        blurHash: "LRRW0b?b00-;~qj[%Mt700WB4nM{",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_0016_LGS2500.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L78;JiInXO-W~XX7J5$+=}o|J6-V",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_LGS2500.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L797R@InS_-D~DNZI.-C^ktRJ6-C",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_LGS3000.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L78;JhD%Sw-W~WbuJ5$S=}SzEe-C",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_LGS4000_A_Upload.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L98g$|?a-..9?w%LxUtTSjf4V=WZ",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_PS2500_4-Upload.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LND0Go?b?b?b~qWBRjRj%MM{D%IU",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_PS2500_5-Upload_with-Display.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LI9*44kWeTrr_NtRR5nO%#x]R5r=",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/FDS_PS4000_5-Upload---With-LCD.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L9BzIK?v?H=|_Nx]niVYyDbv4nVY",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/Inverter-power-verter-SQ_R.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L17KuM?b_3D%009F%Mt700M{t79F",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG1150i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG1450i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG1550i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG1950i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG2300.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG3500.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG5000.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG750i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG850i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LG950i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1000i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1100i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1600.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1700.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1700PV-SW-L.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LOC6+9t7IUxu~qozIUofxuj[WBa|",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS1700PV-SW_.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LF8XOa%2IBbv_NsmIAXR.7oLM{oz",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS2500.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS3000.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS4000.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS5000.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/LGS900i.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/Livfast-PS-5000-F.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "LLBWe~-;%Mt7~q%Mt7ofxuofRjRk",
        placeholderColor: "#080808",
    },
    "/livguard/inverter images/Livguard-LGS1100iPV_power-verter-Inverter-Front.png": {
        width: 1100,
        height: 1100,
        altText: "",
        blurHash: "L15OKX4nkqDOIAozkW-p00-pD%_3",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/1/hero_image.jpg": {
        width: 3840,
        height: 3841,
        altText: "",
        blurHash: "LE84Pht7xut7~qxut7t7^+t7t7t7",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/1/section3/1.jpg": {
        width: 3840,
        height: 3841,
        altText: "",
        blurHash: "L47A;]Q-=|$j_N9tOENtxuIoxuR*",
        placeholderColor: "#383838",
    },
    "/livguard/landingPages/1/section3/2.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L27T,]}a}@$+yCkq%fIUtli^I:t8",
        placeholderColor: "#483838",
    },
    "/livguard/landingPages/1/section3/3.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L36aSIml^kv~?^56k=Io%hIUofR*",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/2/hero_image.jpg": {
        width: 3840,
        height: 3841,
        altText: "",
        blurHash: "LGB3W+%M%2xu~X%2t7t7~WtRofof",
        placeholderColor: "#484848",
    },
    "/livguard/landingPages/2/other_brands.png": {
        width: 100,
        height: 100,
        altText: "",
        blurHash: "LAFiPk}]9H?a0M0LrsM|MJD~IUs=",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/3/1.jpg": {
        width: 3840,
        height: 2934,
        altText: "",
        blurHash: "L37^fB8^9teT?v0e^+Io~WD*s.WB",
        placeholderColor: "#080808",
    },
    "/livguard/landingPages/3/2.jpg": {
        width: 3840,
        height: 2935,
        altText: "",
        blurHash: "L8A0UY-W=x-W~qEMt7Na-;IoWUWX",
        placeholderColor: "#585858",
    },
    "/livguard/landingPages/3/3.jpg": {
        width: 3840,
        height: 2935,
        altText: "",
        blurHash: "L16a6hH?5k],5+MxyX9[.8IUaLni",
        placeholderColor: "#381818",
    },
    "/livguard/landingPages/3/hero_image.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L88p.V%g-pxu~q?Hxvt7~W%Mxuof",
        placeholderColor: "#382828",
    },
    "/livguard/load-calculator/1.jpg": {
        width: 4973,
        height: 3306,
        altText: "",
        blurHash: "LA9Z+PRj01f+~VRj9GoybbNGoJxt",
        placeholderColor: "#282818",
    },
    "/livguard/logo-128.png": {
        width: 128,
        height: 31,
        altText: "",
        blurHash: "L~R{c9xGae%g~qn%j]t7WVfkj[fk",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/logo-256.png": {
        width: 256,
        height: 63,
        altText: "",
        blurHash: "L|R{c9xGae%g~qjZkCt7WBbHkCfk",
        placeholderColor: "#080808",
    },
    "/livguard/logo-32.png": {
        width: 32,
        height: 8,
        altText: "",
        blurHash: "L{R.=R$*WByD~qs:j[ozRjofa|a|",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/logo-512.png": {
        width: 512,
        height: 126,
        altText: "",
        blurHash: "L~R.[ZxGae%g~qn%kCt7WBbHkCj[",
        placeholderColor: "#080808",
    },
    "/livguard/logo-64.png": {
        width: 64,
        height: 16,
        altText: "",
        blurHash: "L]R.[Z$jjZ%g~qoLoftRRjfkofj[",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/Batteries/Battery -1550TT/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LNHuhXaf|_}Yv~S2o2WV1HNaS#J7",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1550TT/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L267QHIA0x^+}YNGT0,rI9w|yD9s",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1550TT/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LQLg-B?It7_3~q?HIUD%%gS1MyIU",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1550TT/inforgraphic/1.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LwHlGOWB}Z,@aeayWVj[EfayJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1550TT/inforgraphic/2.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "L267TP9F1G^+}tIUo},@0xwf=}IT",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1550TT/inforgraphic/3.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LML;dG^+IU?b~q?bM{IU%gR*MxM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1554STJ/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LQGiH0jZ}F].#mS2n*jt9[NaNuNa",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1554STJ/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L36svsEL1H}t=eNGt7$P9[,Exu5k",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1554STJ/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LTLNrl%2IU%M~q?bRjMx%gkWf8ae",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1554STJ/infographic/1.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LxH95yWB}Z$jjFayayj[EfayJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1554STJ/infographic/2.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "L26Zzt0y1v}[^QIU%2$j1b;2=y9[",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1560STT/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOH8?Kn%|_].wJS2n*f65kNaSgJ7",
        placeholderColor: "#181818",
    },
    "/livguard/product/Batteries/Battery -1560STT/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L25;5aM{0{=|].I:b^,XIUrrx^9[",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1560STT/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LQLXMa?Hoz_3~q-;IUD%-;kVRPMx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1560STT/infographic/1.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LwHlDFWB}Z$je.ayWVj[EfayJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1560STT/infographic/2.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "L25;EyE11H^k}tIUtR,@5*rX=}Io",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1560STT/infographic/3.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LML}1?_3Io?b~q?bMxIAx]RjM{Rj",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1584TT/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LNH+2~af]n}Yv~SLsVWV0|NabbJ7",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1584TT/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L36jXsE10y}[=eRjozwd9sxG%M9t",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1584TT/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LQLqRy?Ioz_3~q-;IUIA%gS1MyIU",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1584TT/infographic/1.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LuH+IdWB}Z,@aeayayj[ACayJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1584TT/infographic/2.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "L36jaz9Z1a}[=yM{t7w|0|#-=|EK",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1584TT/infographic/3.jpg": {
        width: 342,
        height: 342,
        altText: "",
        blurHash: "LML;dG^+IU?b~q?bM{IU%gR*MxM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1639TT/A+/1.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEg",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1639TT/A+/2.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "L26jUlE00e^+}FI:S#=KU]%2PB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1639TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LMLqU-^+R*_4~q?bM{IU%Nf*RQMx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1639TT/infographic/1.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvf6}Y$inia|f6fk9[a{J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1639TT/infographic/2.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "L15q6U4.0y~D=eNGxa,s00=|}[4.",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1639TT/infographic/3.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WIot8~W_3s:IU.8W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1645TT/A+/1.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEf",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1645TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L26Z,?IU0e^+}FI:S#=KmRxuPB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1645TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LMLqU-^+R*_4~q?bM{IU%NkBRQMx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1645TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvf6}Y$inia|f6j[9[a{J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1645TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q6U9F0y~D].NGxa,s00=|}[9F",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1645TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LILXMb~WInt8~q_3s:IU.8W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1666TT/A+/1.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEf",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1666TT/A+/2.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "L26jReE00e^+}YI:OX=KU]$+PB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1666TT/A+/3.jpg": {
        width: 3840,
        height: 2456,
        altText: "",
        blurHash: "LMLqU-^+W._4~q?aM{IA%Nf*RPMx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1666TT/infographic/1.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvjZ}Y$jnia|f6j[9[WpJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1666TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q6U4.0{~D=eNGxa,r00=z^k4.",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1666TT/infographic/3.jpg": {
        width: 3840,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WIot8~W_3s:IU.8X5RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1860TT/A+/1.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "LKH*{*R*|_].#SW;sVay0|NuW;I:",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1860TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L15zq4Q-0d?v|^NaTJ;gZ2%3PV0d",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1860TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LQLg-B?HRj?b~q?bRjIUt8R%RjM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1860TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LvHbogjZ}Y$jnia|f6j[9[WpJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1860TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L04^?i8^0e~q|[I:x][W00^R~D00",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1860TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXPj~WIot7_3_3s;IU-=WnRPM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1866TT/A+/1.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEg",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1866TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L26Z:|IT0e^+}FI:S#=Kh}xuPB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1866TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LNLqU-^+R*_3~X?aM{IU%Mf*RQMx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -1866TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvf6}Y$inia|f6j[9[a{J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1866TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q9b9F0y~D].NGxa,s00=|^k9F",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -1866TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WIot8~W_3s:IU.8W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2048TT/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEf",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2048TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L26jRdIU0e^+].I:X8=KmRxuPB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2048TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LMLqU-^,oz~q~q?aIUD%%NW.M{Mx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2048TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvf6}Y$inia|f6j[9[a{J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2048TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q6U9F0y~D].NGxa,s00=|}[4.",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2048TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WIot8~W_3s:IU.8W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2060TT/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEf",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2060TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L26Z:}IT0e^+}FI:X8=KmQxuPB9Y",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2060TT/A+/3.jpg": {
        width: 3840,
        height: 2456,
        altText: "",
        blurHash: "LMLqU-^+W._4~q?bM{IA%NbaRPMx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2060TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvjZ}Y$jnia|f6j[9[a|J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2060TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q6U9F0y~D].NGxa,r00=|^k9F",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2060TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WIot8~W_3s:IU.8W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2066TT/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEf",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2066TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L26jUkIU0e^+].I:X8=KU^%2PB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2066TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LMLz?Y_3o|~q~q?aIUD%x]WnM{Mx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2066TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LuHut%f6}Y$inia|f6fk9[a{J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2066TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q9b4.0y~D].NGxa,s00=|}[4.",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2066TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WM{t8_3_3s:IU-=W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2266TT/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "LJH*{*R*|_}F#SW;soay0|NubHEf",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2266TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L26jRdE10e^+].I:X8=KZN$+PB9Z",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2266TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LMLqU-^,kV_N~q?aIUD%%NbYM{Mx",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2266TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LuHuqvf6}Y$inia|f6fk9[a{J7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2266TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L15q6U4.0y~D=eNGxa,s00=|}[4.",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2266TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXMb~WIot8~W_3s:IU.8W.RPRP",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2360TT/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "LKH*{*R*|_].#SW;sVay0|NuW;I;",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2360TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L15ztBQ-0d?v|xNZTJ;NUu%2PV0K",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2360TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LQLg-B?HWU?c~q?bM{IUtRR%RQM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2360TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LvHbofjZ}Y$jnia|f6j[9]WpJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2360TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L054dP8w0d~q}FIox][q00^k~D00",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2360TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXPj~WIot8_3_3s;IU-=W.RPM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2672TT/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "LKH*{*R*|_].#SW;sVay0|NuW;I:",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2672TT/A+/2.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L15zq4Md0d?v|^NHTJ;gQR-WPV0d",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2672TT/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LQLXMb?HR%?b~q?bRQIUtRR%RjM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/Batteries/Battery -2672TT/infographic/1.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LvHlA8jZ}Y$jnia|f6j[9[WpJ7S2",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2672TT/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L154dQI90{?c]-Rjoz,D0J-W^kDi",
        placeholderColor: "#080808",
    },
    "/livguard/product/Batteries/Battery -2672TT/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LJLXPj~WM{t8_3_3s:IU-=W.RPM{",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1150i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1150i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1150i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1150i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1150i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG1150i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1150i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1150i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%%K%rr+^{f0{M{=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1450i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw|",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1450i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1450i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1450i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1450i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%*K%rr+^{f0{M{=yO?I:NGoz",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1450i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1450i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1450i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG1550i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0EzM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1550i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1550i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1550i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1550i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%*K%rr+^{f0{M{=yO?I:NGoz",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1550i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1550i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1550i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG1950i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw|",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1950i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1950i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG1950i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG1950i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%%K%rr+^{f0{M{=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG1950i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG1950i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG1950i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG750i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG750i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG750i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG750i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG750i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%*PArr+^{f0{NF=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG750i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG750i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG750i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG850i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG850i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG850i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG850i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG850i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%*K%rr+^{f0{NF=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG850i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG850i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG850i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LG950i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFBLM0AWM{wd|_ACNG$kx]J7Rjw{",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG950i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LFGbYa01M}~V0#Sh%1Io#-v}RPNH",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG950i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LVM%cf8_bv?a~Bs:NGM{tRkBV[WB",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LG950i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLgbD4U%#-V~pxaIUNGyr%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LG950i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "L9CE%%K%rr+^{f0{M{=yO?I:NGog",
        placeholderColor: "#180808",
    },
    "/livguard/product/inverter/LG950i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LGHUzy4oE2^*0fT0xtM{~W-7VsNe",
        placeholderColor: "#383838",
    },
    "/livguard/product/inverter/LG950i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOpJT8_SN?H~AxaNGM{NcR*V[jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LG950i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLLghT4.t,-B~q%2MxR*.TxYQ.Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1000i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L$Kdxp-p%Moz~qn%axozkBRjRPni",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1000i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LjNw4kIntQ%1~qxuM{NGtRWBV@t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1000i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LWM%cf8_bv?H~Bs:NGM{o#oeV[WB",
        placeholderColor: "#c8b8a8",
    },
    "/livguard/product/inverter/LGS1000i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLzmq4U%}-V~qxbIUNGyY%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1000i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LyLNlY?Hxuoz~qj[aeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1000i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOf[Uax%M,=~q%MM{Io?vt7M{kW",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1000i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LROyz{4mSN?H~AxaNGM{NcWVV@jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1000i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLL;BQ4.t,-C~q%2MxRj.TxYQ-Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1100i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L$Kd#w-p%Moz~qo0axozkBRjRPni",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1100i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LjNw4kIntQ%1~qxuM{NGtRWBV@t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1100i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LWM%cf8_bv?H~Bs:NGM{o#oeV[WB",
        placeholderColor: "#c8b8a8",
    },
    "/livguard/product/inverter/LGS1100i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLzmq4U%}-V~qxbIUNGyY%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1100i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LyLNlY?Hxuoz~qj[aeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1100i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOf[Uax%M,=~q%MM{Io?vt7M{kW",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1100i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LROyz{4mSN?H~AxaNGM{NcWVV@jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1100i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLL;BQ4.t,-C~q%2MxRj.TxYQ-Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1600/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L%Kd#x-p%2oz~qn%ayozkBRjRPjF",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1600/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LcN^G1Int7$%~qxaM{WB-;s:M{bI",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1600/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LUM@1F8_bv?H~Bs.NGM{kWa{WBa#",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LGS1600/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLzmq4U%}-V~qxaIUNGyY%1MKNa",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1600/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LyLE4-?Hxuoz~qjtaeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1600/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LPO:Ry8^Sg?H~AxZM{M{I=WCV[oM",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1600/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOf[UWUxv$M~q-pRPM{?vt7Mxg3",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1600/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LMLzmr9Ft,-B~q%2MxR*.Tt4Q-R*",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS1700/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L$Kd#w-p%2oz~qn%ayozj[RjRPjF",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS1700/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LcN^G1Int7$%~qxaM{WB-;s:M{bI",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1700/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LUM@1F8_bv?H~Bs.NGM{kWa{WBa#",
        placeholderColor: "#d8d8c8",
    },
    "/livguard/product/inverter/LGS1700/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLzmq4U%}-V~qxaIUNGyY%1MKNa",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS1700/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LyLE4-?Hxuoz~qjtaeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1700/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LPO:Ry8^Sg?H~AxZM{M{I=WCV[oM",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS1700/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOf[UWUxv$M~q-pRPM{?vt7Mxg3",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS1700/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LMLzmr9Ft,-B~q%2MxR*.Tt4Q-R*",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS900i/A+/1.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "L$Kd#w-p%Moz~qo0axozkBRjRPn$",
        placeholderColor: "#282828",
    },
    "/livguard/product/inverter/LGS900i/A+/2.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LjNw4kIntQ%1~qxuM{NGtRWBV@t7",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS900i/A+/3.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LWM%cf8_bv?H~Bs:NGM{o#oeV[WB",
        placeholderColor: "#c8b8a8",
    },
    "/livguard/product/inverter/LGS900i/A+/4.jpg": {
        width: 344,
        height: 220,
        altText: "",
        blurHash: "LOLzmq4U%}-V~qxbIUNGyY%1Q-Na",
        placeholderColor: "#d8d8d8",
    },
    "/livguard/product/inverter/LGS900i/infographic/1.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LLL;BQ4.t,-C~q%2MxRj.TxYQ-Na",
        placeholderColor: "#c8c8c8",
    },
    "/livguard/product/inverter/LGS900i/infographic/2.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LROyz{4mSN?H~AxaNGM{NcWVV@jb",
        placeholderColor: "#e8d8c8",
    },
    "/livguard/product/inverter/LGS900i/infographic/3.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LSOf[Uax%M,=~q%MM{Io?vt7M{kW",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/inverter/LGS900i/infographic/4.jpg": {
        width: 492,
        height: 492,
        altText: "",
        blurHash: "LyLNlY?Hxuoz~qj[aeofRjWBRjaK",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the hi-power jodi/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L9A[J@of0|xD}Zof9[jE5:oJ+]NH",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the hi-power jodi/A+/2.jpg": {
        width: 3840,
        height: 2456,
        altText: "",
        blurHash: "L26aCzw^D%=|HBozM{S1}[sVRjoL",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the hi-power jodi/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LKOf}nIA?]?b~qE19FV[NINGxGs:",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the hi-power jodi/infographic/1.jpg": {
        width: 3841,
        height: 3841,
        altText: "",
        blurHash: "L7D7HvFK1H}Y}ZX8ELr@0#w]rrEg",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the hi-power jodi/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L36@NNxGNG=z7|ofayWo|_n%WBnj",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the hi-power jodi/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LEOplVMx.R~W_39Z8{RjXnNF$kjY",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the rural jodi/A+/1.jpg": {
        width: 3840,
        height: 2457,
        altText: "",
        blurHash: "L9B1#ekC0|xD}Zof9[i_5:oJ+]NH",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the rural jodi/A+/2.jpg": {
        width: 3840,
        height: 2456,
        altText: "",
        blurHash: "L36a9rxFE1-VG@ofNGS2}tn%R*oL",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the rural jodi/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LIOz3?D%.S^+~qD%DiV[NxNGwen%",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the rural jodi/infographic/1.jpg": {
        width: 3841,
        height: 3841,
        altText: "",
        blurHash: "L8C|w8J-1H].}ZX8ELsA0}wvrrEg",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the rural jodi/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L36%yoxGNG=z7|ofayW.|_n%WBn%",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the rural jodi/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LFOz6|My.R~W?b9Z9FRjk=RjxHV@",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the super life jodi/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L9B1#ekC0|$g}Zof9[en5:oJ+]NH",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the super life jodi/A+/2.jpg": {
        width: 3840,
        height: 2456,
        altText: "",
        blurHash: "L36tB-s:E1-VCQofRjNu}tn%R*oL",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the super life jodi/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LIOz3=D%.S^+~qD*DiV@NeNFwfs:",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the super life jodi/infographic/1.jpg": {
        width: 3841,
        height: 3841,
        altText: "",
        blurHash: "L7D7HvFd1H}F}Zbb9[sA0#wvrrEg",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the super life jodi/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L36@NNxGNG=y7|off6SM|_n%WBsA",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the super life jodi/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LEOpiOMx?v~q_39Z8_RQb_NF$koe",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the urban jodi/A+/1.jpg": {
        width: 3841,
        height: 2457,
        altText: "",
        blurHash: "L9A[J@kC0|xD}Zof9[jE5:oJ+]NH",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the urban jodi/A+/2.jpg": {
        width: 3840,
        height: 2456,
        altText: "",
        blurHash: "L36jqJsoE1-VG@ofRjS1^Qn%R*oL",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the urban jodi/A+/3.jpg": {
        width: 3841,
        height: 2456,
        altText: "",
        blurHash: "LJOpfGIA?v^+~qD*DiV[NxRjwen%",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/product/jodis/the urban jodi/infographic/1.jpg": {
        width: 3840,
        height: 3841,
        altText: "",
        blurHash: "L8C|w8Jn1H].}ZX8ELsA0}wvrrEg",
        placeholderColor: "#180808",
    },
    "/livguard/product/jodis/the urban jodi/infographic/2.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "L36@KGxGNG=z7|ofayWo|_niWBn%",
        placeholderColor: "#282828",
    },
    "/livguard/product/jodis/the urban jodi/infographic/3.jpg": {
        width: 3841,
        height: 3840,
        altText: "",
        blurHash: "LFOpiOMx.R~q?vD%9FRjpIRjxHV@",
        placeholderColor: "#f8f8f8",
    },
    "/livguard/temp/Load calculator Bg.jpg": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "LZPyGJ_3S##-|IniWBo1rDRPayoL",
        placeholderColor: "#d88888",
    },
    "/livguard/temp/Load calculator needle.png": {
        width: 56,
        height: 56,
        altText: "",
        blurHash: "LeG+UM~qD%RjM{M{RjWB009F%Mof",
        placeholderColor: "#080808",
    },
};
